### ISSUE TITLE
[Feat] 새로운 쪽지 추가

### ISSUE THREAD

**Issue by skkimeo** [Happiggy/Happiggy-bank-iOS#26]
- [x] UI 확정 후 필요한 변경 사항 반영 #47 
- [x]  현재 활성화된 저금통을 탭하면 쪽지 추가 팝업을 띄운다
    - [x]  팝업 왼쪽 상단에는 취소 버튼, 오른쪽 상단에는 완료 버튼을 띄운다 (변경 가능)
    - [x]  팝업을 띄울 때 배경을 완전히 덮고 블러 처리한 효과를 준다(혹은 단색?)
- [x]  쪽지는 하루에 1개로 제한한다.
    - 단 과거에 작성하지 않은 날짜의 쪽지를 오늘 작성할 수 있다.
    - 예를 들어 오늘이 3/1 이고 2/28 에 쪽지를 작성하지 않았다면, 2/28 의 쪽지를 오늘 작성할 수 있다
- [x]  처음에는 팝업 내용으로 쪽지 날짜 피커를 띄운다
    - [x] 디폴트는 오늘 날짜로 하고, 이미 쪽지를 작성한 날짜는 선택 불가하게 한다
    - [x] #45
    - [x] 오늘 이미 쪽지를 작성했다면 작성하지 않은 날짜 중 가장 빠른 날짜를 디폴트로 한다
    - 자정부터 새벽 2시까지는 오늘과 어제 중 언제 작성할 것인지 물어본다
- [x]  날짜를 선택하면 컬러 피커를 띄운다.
    - [x]  컬러 피커는 5개의 색깔 동그라미가 가로로 쭉 나열되어 있는 형태다
    - [x] 프로 맥스에서는 원형이 아닌 현상 발견
- [x]  컬러를 선택하면 선택한 색상의 쪽지 작성 텍스트뷰를 띄운다
    - 텍스트뷰는 키보드와 영역이 겹치지 않는다
- [x]  텍스트뷰 왼쪽에는 날짜를 띄운다
    - [x]  **날짜를 누르면 데이터 피커를 띄운다?**
- [x]  날짜 라벨 옆에 원형의 컬러 버튼을 띄운다
    - [x]  컬러 버튼을 누르면 일정한 순서에 따라 쪽지 색상이 바뀌게 한다
- [x]  쪽지의 최대 글자수는 100자로 제한한다.
    - ~~placeholder 에 쪽지의 최대 글자수는 100글자라고 알린다~~
    - [x]  쪽지 내용이 100글자를 넘어가면 더 이상 기입되지 않도록 한다.
    - [x]  현재까지 작성한 글자수를 하단에 띄운다.
- [x] 쪽지 색상에 따라 텍스트 색상이 시각적으로 잘 보이도록 변경한다 #47 
- ~~키보드가 올라온 상태에서 텍스트뷰를 누르면 키보드를 내린다~~
- ~~쪽지의 내용(최소 1글자)이 없는 상태로 완료 버튼을 누르면 알림을 띄운다.~~
- [x]  내용이 유효한 상태에서 완료 버튼을 누르면 쪽지 데이터를 코어데이터로 보내고, 키보드와 팝업을 내린 다음, 홈 뷰에 쪽지가 하나 추가되었음을 알린다
    - 홈 뷰의 유리병에서 쪽지가 하나 추가되는 애니메이션을 나타낼 수 있도록
- ~~논의 후 컬러피커 삭제 가능~~
  - 베타 테스트 후 결정하기로 함
- [x] 날짜 라벨이랑 텍스트뷰 정렬이 미묘하게 안 맞음 텍스트뷰 기본 inset 때문으로 추정 조정 필요 #47

**Comment by skkimeo** [comment]
완료
